### ISSUE TITLE
Contact's AccountNumber is missing in CreditNotes response

### ISSUE THREAD

**Issue by ldsenow** [XeroAPI/Xero-OpenAPI#104]
As title

**Comment by MatthewSteeples** [comment]
Is this a request for a single credit note or a request for all credit notes?

**Comment by ldsenow** [comment]
I found it is missing in all credit notes response, however, I didn't check the single one response

**Comment by MatthewSteeples** [comment]
The API only gives you very minimal details (Id and Name) if you're requesting more than one entity. If you request a single entity then you usually get the full referenced entities with it

**Comment by ldsenow** [comment]
Then why the Invoices response has the full details including the AccountNumber? Should they be consistent?

**Comment by MatthewSteeples** [comment]
That's a good question! I'm afraid I'm only a user of the API and don't work for Xero so you'll have to wait for member of support to respond to that. I would expect them to be consistent. Are you using Paging in the Invoices endpoint? If so, that's got a slightly different set of rules.

**Comment by SidneyAllen** [comment]
@MatthewSteeples and @ldsenow 

The level of detail returned for objects differs when reading ALL objects or a single object from API endpoints. 

We've chosen to not create different objects based on the level of detail returned by the API - this is a more DRY approach.
