### ISSUE TITLE
Missing POST Endpoints

### ISSUE THREAD

**Issue by toby2g** [XeroAPI/Xero-OpenAPI#108]
Hi,

I've gone through the official developer documentation (https://developer.xero.com/documentation/api/api-overview) for several of the Accounting API resources. There appears to be mention of the POST method for several endpoints, however the API specification here shows that the PUT method is the only one offered.

An example of this would be the `/Contacts#bulk` endpoint. Should this endpoint, and others like it, have a 'POST' method implemented? 

Thanks.

**Comment by SidneyAllen** [comment]
Hi @toby2g 

I've made this change for all endpoints that support bulk create.  The one exception is TaxRates which does not have an ID and uses POST to update TaxRates on the /taxrate endpoint.

**Comment by toby2g** [comment]
Thank you so much!
