### ISSUE TITLE
UpdatedDateUTC format

### ISSUE THREAD

**Issue by stevenbrookes** [XeroAPI/Xero-OpenAPI#109]
Hi

We are using the Accounting API via a library generated using swagger codegen.  All working well apart from the field UpdatedDateUTC.  In the OpenAPI file this is defined as a a string of type date-time.  According to OpenAPI this means the string should RFC3339 format.  That's somethign like this  1985-04-12T23:20:50.52Z.

However when we query for example GET Accounts.  The value for this field looks like for example "/Date(1576107758447+0000)"  The number in there seems to be the number of milliseconds since UNIX epoch.  

The effect of this is that the unserialisation of the response fails as it can't turn that string into a in this case PHP DateTime.  

I see that the current format for dates isn't likely to change  https://developer.xero.com/documentation/api/requests-and-responses  so I think the only solution currently would be to remove the format line from all the UTC fields.

Let me know what you think.

Regards

Steve

**Comment by SidneyAllen** [comment]
Hi @stevenbrookes 

You've identified one of the quirks in Xero's accounting API endpoints.  As you correctly pointed to in our docs, we return datetime in the MSJSON format.   Depending on the programming language some customization around date deserializing may be necessary.

`
$match = preg_match( '/([\d]{13})/', $data, $date );
$timestamp = $date[1]/1000;
                
 $datetime = new \DateTime();
 $datetime->setTimestamp($timestamp);
           
 $result = $datetime->format('Y-m-d H:i:s');
 $date = new \DateTime($result);
 return $date;`

We won't be removing the UTC fields in the OpenAPI spec but you are free to fork and customize if you wish.

**Comment by stevenbrookes** [comment]
Hi Sidney

I don’t expect you to remove the fields. But the format for the string in the spec is incorrect. If you just remove the format element of the field then it’ll be returned by the generated client files as a string we can then process as you suggest. 

Otherwise the Api spec files are unusable for anybody  generating client files automatically using swagger code gen for example. 

Regards

Steve
