### ISSUE TITLE
Total field and more are null on CreditNotes when filtering by CreditNoteID

### ISSUE THREAD

**Issue by george-y** [XeroAPI/Xero-OpenAPI#13]
Using the CreditNoteID filter we get responses with lots of null fields. 

Using the Where filter instead (filtering by date in our case) we get responses that are correctly populated, for the exact same credit note. 
 
Observed using the Java SDK.

**Comment by SidneyAllen** [comment]
Hi @george-y 

There are naturally going to be a lot of fields that are null as many are not required.  I did find one issue with the OpenAPI Spec.  Credit Notes did not have a "Payments" array defined.  So I'm correcting that and will release a new version of the Java SDK. 

I'm compared the JSON data returned to the parsed Java Object and this is the only "missing" property I could identify.
