### ISSUE TITLE
Uncertified app limitation

### ISSUE THREAD

**Issue by ldsenow** [XeroAPI/Xero-OpenAPI#140]
Hi,

I am hitting oauth2 limitation as screenshot below
![image](https://user-images.githubusercontent.com/177045/74116123-34f1d480-4c06-11ea-9617-bcf269df66a6.png)

However, I checked the my Connected App section as below:
![image](https://user-images.githubusercontent.com/177045/74116135-4c30c200-4c06-11ea-996e-399245787ccd.png)

I don't see other connected app other than the Square one.

Is it a bug?

**Comment by MJMortimer** [comment]
Hey @ldsenow, 
Thanks for bringing this to our attention. Looks like there is a bug around this. 

We'll be looking to push out a fix for the bug this morning (NZT)

**Comment by MJMortimer** [comment]
This should be fixed now @ldsenow. 
Can you please confirm you;re no longer seeing this issue?

**Comment by ldsenow** [comment]
@MJMortimer Thanks and verified its been fixed.

**Comment by ldsenow** [comment]
@MJMortimer A quick question on the uncertified app OAuth2 connection limit. The doc is saying 25 connections. Does it mean concurrent active connections? Or all time connections even if the connection is expired

**Comment by dev-welli** [comment]
@ldsenow 
It is "the other side" of the limit.
An uncertified app can only be connected to 25 tenants/organisations
A tenant/organisation can only be connected to two uncertified apps
