### ISSUE TITLE
Can we just set the tenant ID on the Configuration class?

### ISSUE THREAD

**Issue by SidneyAllen** [XeroAPI/Xero-OpenAPI#149]
All API endpoints require you pass the Xero Tenant ID into each method call. 

**Example ...**
$api->getContacts($tenantId);
$api->getContact($tenantId, $contactId);
$api->createContactsContacts($tenantId, $contactsList);

We made this choice due to since an access token is user based now and can be used to connect to 1 to N Xero orgs.  Many apps are used by Accountants who will leverage multi-org authentication in the future and passing the Tenant Id into a method allows developers to create a Singleton of the AccountingApi class and then loop over an array of orgs and pass in unique tenant ids.  

The proposed alternative pattern (PHP example

Set the tenantId on the configuration like the access token

$config = Configuration::getDefaultConfiguration();
$config->setHost('https://api.xero.com/api.xro/2.0);
$config->setAccessToken($accessToken);
$config->setTenantId($tenantId);

**Reasoning**
Right now we have to keep track of the tenantId and inject it from somewhere, every time we want to use the API, that means that in a system where we use dependency injection (e.g. Laravel) we can't just inject an instance of AccountingApi that's preconfigured, we need to inject the AccountingApi instance and either load the tenantId from a cache, or inject something else that knows about it.

**Discussion**
We are opening this topic up for discussion.  We know different languages and developers have different preferences and want to hear both pro and con view points on this.

To set expectations around these discussions, we are focused on stability around SDKs and therefore no decision will be made on large scale requests like this until end of 2020.

**Comment by IanSimpson** [comment]
To get around this (and particularly to make it cleaner migrating some legacy code), I just put together a simple wrapper class (which also deals with OAuth token storage/renewal etc.). The guts of it is:

```
function __call($method, $arguments) {
	try {
		return $this->instance->$method($this->tenant, ...$arguments);
	} catch(ApiException $e) {
		//Do some stuff
	}
}
```

I've constructed `@method` PHPDoc declarations from the AccountingApi class to ensure code completion etc. works fine still. Seems to work well.

**Comment by fooman** [comment]
I think a wrapper class is the way to go. Keeps existing, already migrated projects working without further changes.

**Comment by BTPDarren** [comment]
This is basically what I have done now with my Wrapper. you set up the configuration and then just call the methods for what you need to do.

Mine is in .NET.

**Comment by SerKnight** [comment]
Agreed that a wrapper class is the best individual architecture decision. It keeps in line with Xero's API which is explicit about its header req for the tenant ID, and baking this into the spec and SDKs assumes too much about systems IMO.

Closing but open to more discussion.
