### ISSUE TITLE
Contact could not be found

### ISSUE THREAD

**Issue by ldsenow** [XeroAPI/Xero-OpenAPI#158]
Hi guys,

I would like to know if below if it is possible to happen:

1. An invoice without a contact
2. An invoice has a 'deleted' contact so I can't get this contact from the contact list API request
3. Is the contact info of an invoice a snapshot of time?

I am trying to round off the edge cases and please advise.

**Comment by MattR-Api** [comment]
Hi @ldsenow 

As this isn't an OpenAPI specific question, I'll shut down this issue, however we're still more than happy to help. 

If you could please email us at api@xero.com with your question, we'll be point you in the right direction. 

Kind Regards

Matt
