### ISSUE TITLE
ContactNumber in Contact should not be read only

### ISSUE THREAD

**Issue by vvlevykin** [XeroAPI/Xero-OpenAPI#16]
From the documentation:
> If possible, we recommend you limit filtering to the following optimised elements Status, InvoiceID, InvoiceNumber, Date, Reference, Contact.ContactID, Contact.Name, **Contact.ContactNumber** and Type. The most efficient queries are simple "==" on these fields.

The current spec doesn't allow the `ContactNumber` to be set when initialising the `Contact`.

**Comment by SidneyAllen** [comment]
Hi @vvlevykin 

I've updated the spec and pushed new version of Java SDK 2.2.17 (in case you are using that)
