### ISSUE TITLE
Add summarizeError param to createPayments

### ISSUE THREAD

**Issue by SidneyAllen** [XeroAPI/Xero-OpenAPI#167]
Based on this issue.
https://github.com/XeroAPI/Xero-NetStandard/issues/154

Need to validate the API functionality.

**Comment by jenksguo** [comment]
@SidneyAllen 

Issue with the template on handling boolean parameters not an API spec issue.

Thanks for your suggestion. 

The fix is now tested and implemented. 

NetStandard SDK 0.4.3 has this addressed now.
