### ISSUE TITLE
API does not respond when trying to create purchase orders with incorrect account id

### ISSUE THREAD

**Issue by can3p** [XeroAPI/Xero-OpenAPI#198]
Hi! I wanted to post this bug report in the community portal, but I seems like I need additional permissions to do so, so I'll post my report there, since it's partially about spec too.

While doing the integration with xero I encountered an easily reproducible behavior that doesn't look correct, especially given that it behaves different for different content type.

Here is an xml payload:

```xml
<PurchaseOrders>
  <PurchaseOrder>
    <Contact>
      <ContactID>BROKEN</ContactID>
    </Contact>
    <Date>2020-04-28T14:00:00</Date>
    <LineAmountTypes>Exclusive</LineAmountTypes>
    <LineItems>
      <LineItem>
        <Description>Coffee Cup</Description>
        <Quantity>4.3400</Quantity>
        <UnitAmount>395.00</UnitAmount>
        <AccountCode>300</AccountCode>
      </LineItem>
      <DeliveryDate>2020-04-30</DeliveryDate>
      <Reference>1234</Reference>
      <DeliveryAddress>Hamburg</DeliveryAddress>
      <AttentionTo>John Doe</AttentionTo>
      <Telephone>+88885</Telephone>
    </LineItems>
  </PurchaseOrder>
</PurchaseOrders>
```

Since contact id is invalid I get a response with status 400 and body:

```xml
<ApiException xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <ErrorNumber>14</ErrorNumber>
    <Type>PostDataInvalidException</Type>
    <Message>Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).</Message>
</ApiException>
```

If I switch to json and send a body like this:

```json
{
	"PurchaseOrders":
	[
		{
			"Contact":
			{
				"ContactID":"BROKEN"
			},
			
			"LineItems":[
				{"Description":"Tomatoes","Quantity":1,"ItemCode":"DevD"},
				{"Description":"Potatoes","Quantity":1,"ItemCode":"GB1-White"},
				{"Description":"Water","Quantity":1,"ItemCode":"PMD"}
			],
			"DeliveryDate":"2020-04-30",
			"Reference":"1234",
			"DeliveryAddress":"Hamburg",
			"AttentionTo":"John Doe",
			"Telephone":"+888885"
		}
	]
}
```

api responds with 500 status and body is never sent, hence a client that was generated base on openapi spec hangs forever. Given a correct account number the same payload works fine.

Unfotunately, json is the only format mentioned in the spec, so it's not possible to work it around by generating a client using a different content type.

One more note. It appears that purchase orders endpoint supports not only arrays but individual objects as well. So it's possible to send a payload like this:

```json
{
	"Contact":
	{
		"ContactID":"BROKEN",
		"PaymentTerms":{"Bills":{},"Sales":{}},
		"BatchPayments":{},
		"Balances":{
			"AccountsReceivable":	{},"AccountsPayable":{}
		}
	},
	
	"LineItems":[
		{"Description":"Tomatoes","Quantity":1,"ItemCode":"DevD"},
		{"Description":"Potatoes","Quantity":1,"ItemCode":"GB1-White"},
		{"Description":"Water","Quantity":1,"ItemCode":"PMD"}
	],
	"DeliveryDate":"2020-04-30",
	"Reference":"1234",
	"DeliveryAddress":"Hamburg",
	"AttentionTo":"John Doe",
	"Telephone":"+888885"
}
```

In case of correct payload purchase orders are created, otherwise a correct error is returned:

```json
{
  "ErrorNumber": 14,
  "Type": "PostDataInvalidException",
  "Message": "JSON for post data was invalid,Error converting value \"BROKEN\" to type 'System.Guid'. Path 'Contact.ContactID', line 4, position 23."
}
```
Unfortunately this payload is not described in openapi and hence generated clients do not provide a way to submit this payload.

Expected behvaior: I would expect to get a 200 status code with an array of purchase orders. For the ones with incorrect account number I would expect to see an error as describe in the documentation: 

If you are entering many purchase orders in a single API call then we recommend you utilise the summarizeErrors parameter which provides a response format that shows validation errors for each purchase order. Note that each Purchase Order is returned with a status element which will either contain the value OK or ERROR. If a purchase order has an error then one or more validation errors will be returned.

**Comment by SidneyAllen** [comment]
@can3p - Thanks for the feedback.

I've tested this with our Java and PHP SDKs.  The Java SDK catches the invalid string before posting to the API, but the PHP does throw 500 error when you use a ContactId = "BROKEN".

I'm not sure this is a valid test case.  I tried a second time with our PHP SDK and used a properly formatted, but invalid GUID ContactId= "00000000-0000-0000-0000-000000000000" and received a 200 response with a validation error for the Purchase Order.

Nonetheless, I'll be sharing this bug with our API team so they can prioritize fixing it.  This isn't an issue with the OpenAPI spec per se but with the API.   Client SDKs we generate from these spec only support JSON as we felt supporting serialization for both JSON and XML was not necessary and between the two JSON is the preferred req/resp format.

While the API supports both an Object OR an Array of Objects when creating a Purchase Order, OpenAPI specs only allow for a single path/verb combination. For this reason, we've chosen to include the plural create as you can create a single or plural objects using this method.
