### ISSUE TITLE
Payment `IsReconciled` flag not showing on Batch Payments

### ISSUE THREAD

**Issue by IanSimpson** [XeroAPI/Xero-OpenAPI#205]
I'm not quite sure that this is the right place for this bug report, but I can't find a better place, so here we go! I'm using the PHP client library, but the same results will happen with any client.

--

I'm tracking when payees deposit checks (and they are reconciled) by doing `$xero->getPayments()` each day and tracking which ones the `IsReconciled` flag flips on during that day. Each Payment is related to one Invoice, and this works great.

However I've hit a problem with inconsistent behaviour where several invoices are paid with a single transaction. Here's a very abridged output from my `getPayments()` call:

```
[0] => XeroAPI\XeroPHP\Models\Accounting\Payment Object	(
	[invoice] => XeroAPI\XeroPHP\Models\Accounting\Invoice Object (
		[type] => ACCPAY
		[contact] => ...
		[line_items] => ...
		[date] => ...
		[invoice_number] => 1517
		[status] => PAID
		[total] => 435
		[invoice_id] => 987ddb2a-2271-46f8-a420-0b4cf53b188f
		[payments] => Array (
			[0] => XeroAPI\XeroPHP\Models\Accounting\Payment Object(
				[invoice] => 
				[credit_note] => 
				[prepayment] => 
				[overpayment] => 
				[invoice_number] => 
				[credit_note_number] => 
				[account] => 
				[code] => 
				[date] => DateTime Object(
					[date] => 2020-04-16 19:00:00.000000
					[timezone_type] => 3
					[timezone] => America/Chicago
				)
				[currency_rate] => 1
				[amount] => 435
				[reference] => 29172
				[is_reconciled] => 
				[status] => 
				[payment_type] => 
				[updated_date_utc] => 
				[payment_id] => 75421a0a-b356-45e7-ab0f-129e261c1132
				[bank_account_number] => 
				[particulars] => 
				[details] => 
				[has_account] => 
				[has_validation_errors] => 
				[validation_errors] => 
			)
		[amount_due] => 0
		[amount_paid] => 435
		[fully_paid_on_date] => DateTime Object (
			[date] => 2020-04-16 19:00:00.000000
			[timezone_type] => 3
			[timezone] => America/Chicago
		)
		[amount_credited] => 
		[updated_date_utc] => DateTime Object (
			[date] => 2020-04-17 14:05:41.000000
			[timezone_type] => 3
			[timezone] => America/Chicago
		)
	)
	[date] => DateTime Object (
		[date] => 2020-04-16 19:00:00.000000
		[timezone_type] => 3
		[timezone] => America/Chicago
	)
	[currency_rate] => 1
	[amount] => 435
	[reference] => 29172
	[is_reconciled] => 
	[status] => AUTHORISED
	[payment_type] => ACCPAYPAYMENT
	[updated_date_utc] => DateTime Object (
		[date] => 2020-04-17 14:05:41.000000
		[timezone_type] => 3
		[timezone] => America/Chicago
	)
	[payment_id] => 99193d93-bfea-4ab5-bb44-e05c4c43f296
	[has_account] => 1
)
```

As you can see, this has returned a Payment (99193d93-bfea-4ab5-bb44-e05c4c43f296) which clears an Invoice (987ddb2a-2271-46f8-a420-0b4cf53b188f). 

Confusingly however, this Invoice lists a single Payment, but the Payment, but with a different GUID (75421a0a-b356-45e7-ab0f-129e261c1132).

Looking in the Xero web interface, that GUID (75421a0a-b356-45e7-ab0f-129e261c1132) is referred to as a `bankTransactionID`, and the title on the page is "Batch Payment".

`$xero->getPayment('75421a0a-b356-45e7-ab0f-129e261c1132');` returns nothing
`$xero->getBankTransaction('75421a0a-b356-45e7-ab0f-129e261c1132');` returns nothing
`$xero->getBatchPayments($date, '', 'UpdatedDateUTC');` returns nothing

It appears at that whatever object is represented by GUID 75421a0a-b356-45e7-ab0f-129e261c1132 is invisible from the API. In practice this appears to be some sort of psuedo-payment which groups together several other Payments (but isn't a BatchPayment).

The actual problem that this is causing is around the `IsReconciled` flag. In this case, the money has changed hands and been reconciled. Going through the web interface to see the "payment" 75421a0a-b356-45e7-ab0f-129e261c1132 shows it as reconciled. However this information doesn't seem to propagate out to the individual Payment which is accessible through the API - you can see `is_reconciled` above is showing blank.

My expected behaviour is that when an Invoice payment is reconciled, that all relevant Payment objects show as reconciled.

**Comment by kchandola** [comment]
Hi Ian, thanks for raising the issue. From what you’re describing in the web UI, it sounds like those payments were indeed part of a batch payment. You’ve then uncovered a couple of deficiencies in how the API returns the single payment objects that makes things confusing:

1. There is no identifier on those payments that tells you they belong to a batch payment
2. The reconciled status of those payments doesn’t reflect the status from the batch (i.e. if the batch payment is marked as reconciled the individual payments are still returned unreconciled)

That said, we would expect you to be getting a response when querying for all BatchPayments in that organisation. You should also be able to use the bankTransactionID param from the url of the web UI and use it to retrieve the individual batch payment e.g. GET https://api.xero.com/api.xro/2.0/BatchPayments/75421a0a-b356-45e7-ab0f-129e261c1132

If you get in touch with support with some more details about the particular app and the org we can check the logs to troubleshoot what’s happening. Perhaps it’s a problem at the SDK level.

**Comment by SidneyAllen** [comment]
@IanSimpson - this doesn't appear to an issue that can be solved by modifying the OpenAPI specification but is a deficiency  API level, and I'll be closing this issue.

**Comment by kchandola** [comment]
Hi @IanSimpson, I am happy to confirm that with the latest release, we have fixed the above bug around IsReconciled. From now on, when you retrieve payments via the payments endpoint they will show IsReconciled=true if the corresponding batch payment has been reconciled.
No changes on the invoices endpoint though.
