### ISSUE TITLE
'StatusAttributeString' property is missing from Accounting.Payment model class

### ISSUE THREAD

**Issue by adamsadler** [XeroAPI/Xero-OpenAPI#211]
The latest OpenAPI spec (2.1.2) added the `summarizeErrors` flag when batch-adding Payments, and this has since been included in the NetStandard API (https://github.com/XeroAPI/Xero-NetStandard/releases/tag/v2.2.0).

However, the generated Payment model class lacks the `StatusAttributeString` property that is needed when using `summarizeErrors=false`.

**Comment by adamsadler** [comment]
I should add to this that I'm aware the issue title and description make this sound like an SDK issue - but I gather the fix would actually be making changes to the yaml files in this repo?

In fact, I think I've figured out the lines to add, but I'm not 100% sure!

**Comment by SidneyAllen** [comment]
@adamsadler - we've made the change in version 2.1.3
https://github.com/XeroAPI/Xero-OpenAPI/releases/tag/2.1.3

watch for the next release of the SDK built from this version of the spec
