### ISSUE TITLE
Accounting: GET Contact accepts non-uuids as well

### ISSUE THREAD

**Issue by kralikba** [XeroAPI/Xero-OpenAPI#216]
`accounting-yaml/xero_accounting.yaml:2638` states that the IDs must be UUIDs. This is incorrect as not only Contact IDs but Contact Numbers (external identifiers; custom strings) are accepted by the API as well.

**Comment by SidneyAllen** [comment]
@kralikba - I've added a method "getContactByContactNumber"  this will accept a ContactNumber argument.  This is in release 2.1.4 of the spec
