### ISSUE TITLE
The bankfeeds-spec is missing schema-type for Pagination

### ISSUE THREAD

**Issue by cjaeriksson** [XeroAPI/Xero-OpenAPI#227]
The yaml document is missing the schema-type for the Pagination-schema:

    Pagination:
      properties:
        page:
          type: integer
          example: 1
          description: Page number which specifies the set of records to retrieve. Example - https://api.xero.com/bankfeeds.xro/1.0/Statements?page=2 to get the second set of the records. When page value is not a number or a negative number, by default, the first set of records is returned.
        pageSize:
          type: integer
          example: 10
          description: Page size which specifies how many records per page will be returned (default 50). Example - https://api.xero.com/bankfeeds.xro/1.0/Statements?pageSize=100 to specify page size of 100.
        pageCount:
          type: integer
          example: 1
          description: Number of pages available
        itemCount:
          type: integer
          example: 2
          description: Number of items returned

**Comment by SidneyAllen** [comment]
@cjaeriksson - I've looked at the bankfeed spec and there is a pagination component.

https://github.com/XeroAPI/Xero-OpenAPI/blob/4e7908d32662ba0b74fdf8552e5be315e8377bcd/bankfeeds-yaml/xero_bankfeeds.yaml#L680

It is used in the "Statements" component.
https://github.com/XeroAPI/Xero-OpenAPI/blob/4e7908d32662ba0b74fdf8552e5be315e8377bcd/bankfeeds-yaml/xero_bankfeeds.yaml#L674

**Comment by cjaeriksson** [comment]
@SidneyAllen I think you misunderstood me. What I am saying is that the Pagination-schema has no type-property. It should have:

type: object

**Comment by SidneyAllen** [comment]
@cjaeriksson - got it - I've added type:object in release 2.2.1

**Comment by cjaeriksson** [comment]
Awesome - thanks @SidneyAllen
