### ISSUE TITLE
Request: LineItemID missing on Credit Notes

### ISSUE THREAD

**Issue by balazskiss1985** [XeroAPI/Xero-OpenAPI#239]
## Missing LineItemID

Could you please consider adding the LineItemID to the CreditNotes in the future.

On the demo sample data you may run the following:

```
https://api.xero.com/api.xro/2.0/creditnotes/694c1f99-8085-416c-9ace-40f911303229
```

![image](https://user-images.githubusercontent.com/27040328/85965775-11b1a100-b9be-11ea-91f8-a15e682d88f0.png)

As you can see on BankTransactions this has been added already

```
https://api.xero.com/api.xro/2.0/BankTransactions/b9d7c42c-506a-4e56-a8a1-a41330580834
```

![image](https://user-images.githubusercontent.com/27040328/85965894-7ec53680-b9be-11ea-9b58-a54d47f4be3d.png)

**Comment by SidneyAllen** [comment]
@balazskiss1985 - this is a known issue with the API and therefore can't be addressed in the OpenAPI specs.  These specifications are drawn from the existing API and used for generating client SDKs, but are not used to generate the APIs themselves.

I will raise this with our API team.
