### ISSUE TITLE
Credits/Overpayments/Prepayments dates differ depending on how individual invoice is requested from API

### ISSUE THREAD

**Issue by timwiel** [XeroAPI/Xero-OpenAPI#266]
It seems that when using the Invoices endpoint the applied credit/overpayments/credits date returned via JSON and XML is different based on how the an individual invoice is requested. 

A direct invoice request returns the "allocation" date as the invoice date whereas other type of querystring request (which is what the https://github.com/XeroAPI/xero-php-oauth2 uses as it's uri request type) returns the date the "creditnote / prepayment or overpayment was originally created not allocated.

Is this on purpose for any reason? 

**For example:**
https://api.xero.com/api.xro/2.0/invoices/4766401f-5957-4a0e-9e55-54b79bc543bb
results in the "allocations" being returned with each date being the same as the invoice date

![image](https://user-images.githubusercontent.com/21289335/90510343-e9207900-e1ae-11ea-97b7-c581ace5c73b.png)

however https://api.xero.com/api.xro/2.0/Invoices?IDs=4766401f-5957-4a0e-9e55-54b79bc543bb returns the "allocations" with their original creation date.
![image](https://user-images.githubusercontent.com/21289335/90511306-63053200-e1b0-11ea-8cd3-ea4f313a1a28.png)

**Comment by SidneyAllen** [comment]
@timwiel Thank you for reporting this.

We've confirmed this is an issue with the API and a bug report has been created APIB-1814.

This can not be resolved through our OpenAPI specifications, so I'll be closing this case and updating it once the bug has been resolved.

**Comment by wobinb** [comment]
This has now been resolved at API level. The dates will now be correct no matter what format the request is in.
