### ISSUE TITLE
DELIVERY address type enums should not be available for contacts

### ISSUE THREAD

**Issue by jenksguo** [XeroAPI/Xero-OpenAPI#329]
## Expected Behavior

Contact schema Address Type should only have POBOX & STREET enum options. 
Organisation Address Type can have POBOX, STREET & DELIVERY

## Current Behavior

Both Contact and Organisation share the same Address Type Enum options. 

## Possible Solution

Separating the two address type enums in OAS. 

## Steps to Reproduce (for bugs)

1. Create an contact with address type of DELIVERY
2. the address will be "swallowed"

**Comment by SidneyAllen** [comment]
@jenksguo - fixed in 2.7.0
https://github.com/XeroAPI/Xero-OpenAPI/releases/tag/2.7.0
