### ISSUE TITLE
[Bank Feeds] API description statementID vs statementId

### ISSUE THREAD

**Issue by judgej** [XeroAPI/Xero-OpenAPI#379]
The path parameter for the `getStatement` operation has a different name in the two places it is declared. In the clients we generate from this, the `statementId` parameter does not work as a result.

https://github.com/XeroAPI/Xero-OpenAPI/blob/master/xero_bankfeeds.yaml#L512

## Expected Behavior

Code generates as expected - the defined path parameter gets inserted into the path template as expected.

## Current Behavior

This fragment of generated code illustrates the problem:

```php
        $resourcePath = '/Statements/{statementID}'; // <--- placeholder is not proper camelCase
...
            $resourcePath = str_replace(
                '{' . 'statementId' . '}', // <--- matching on camelCase
                ObjectSerializer::toPathValue($statementId),
                $resourcePath
            );
```

In this generated code, using a case-insensitive match should work around this issue, but there are a hundred other languages and tools that need this to be consistent.

## Possible Solution

Change the `statementID` path template placeholder to `statementId` here:

https://github.com/XeroAPI/Xero-OpenAPI/blob/master/xero_bankfeeds.yaml#L512

## Steps to Reproduce (for bugs)

1.
2.
3.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by judgej** [comment]
Can do a PR if that helps. Just need to get some other work out the way first.

**Comment by SidneyAllen** [comment]
Resolved https://github.com/XeroAPI/Xero-OpenAPI/releases/tag/2.10.1
