### ISSUE TITLE
[Bank Feeds] undocumented 400 response (createFeedConnection)

### ISSUE THREAD

**Issue by judgej** [XeroAPI/Xero-OpenAPI#380]
I'll come back with more details, but just as a placeholder for now, here is an overview.

Creating a bank feed connection, I got a rejection with a `400` error. The OpenAPI description shows no response payload for a `400`. This is the payload I got:

```json
{
   "items":[
      {
         "accountToken":"c12345-cld6et3q6...sw8w4",
         "status":"REJECTED",
         "error":{
            "type":"feed-already-connected-in-current-organisation",
            "title":"Feed Connection Failed",
            "status":409,
            "detail":"The AccountToken, AccountNumber or AccountId is already connected to another Xero Bank Account in the selected Xero Organisation."
         }
      }
   ]
}
```

Note `status` in the payload is `409`, but the HTTP response was `400`.

This message format is not consistent with anything I can see in the OpenAPI description.

The response is also inconsistent with the human-readable documentation. It is the `items` array wrapper which appears to be new in the API implementation, but not documented. The `400` being returned instead of a `409` makes sense if there is a list of errors, since each error could have a different status, and so they all need collecting under a single HTTP response status code.

https://developer.xero.com/documentation/bank-feeds-api/feed-connections-errors

## Possible Solution

Fix the OpenAPI description :-)

## Steps to Reproduce (for bugs)

1.
2.
3.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by judgej** [comment]
There are a number of examples in the OpenAPI description that get *close* to the response payload that I get back, but none of them quite there. For example, one has a single error header and wraps errors in an `errors` array, rather than an `items` array with a header for each error.  Also `items` appears *only* in the examples, and not in any of the endpoint definitions, so none of those examples could ever be supported by the API schema.

I'm not sure how to get my hands on the full technical documentation to recommend the changes. If there is anything that could be made available to me, I'll be happy to contribute to the OpenAPI description, but with an OAuth 2.0 deadline looming, time is tight.

**Comment by SidneyAllen** [comment]
@rdemarco-xero - can you look into this issue to see what modifications might be required for example error responses

**Comment by rdemarco-xero** [comment]
@SidneyAllen - I brought this to the Bankfeeds API PM. She confirmed the [documentation](https://developer.xero.com/documentation/bank-feeds-api/feed-connections-errors#http409) should be revised to match the behavior Jason has captured. I will put in a PR to have the developer site updated along with a PR for the revision to the Bankfeeds spec.

**Comment by SidneyAllen** [comment]
@rdemarco-xero - has this issue been resolved?

**Comment by rdemarco-xero** [comment]
Yes the spec was updated and merged. This can be closed.
