### ISSUE TITLE
Overpayment missing reference field

### ISSUE THREAD

**Issue by andrews05** [XeroAPI/Xero-OpenAPI#401]
Hi

Overpayments seem to be missing the reference field.
(Similar to a previous issue for Prepayments, #139).

[edit]
Looks like there's still an issue with Prepayment references. The reference field appears to contain the prepayment number, while there's no actual field for the prepayment number and the real reference is missing.

**Comment by SidneyAllen** [comment]
@andrews05 - the API docs for Prepayment has the following ...

Reference | Returns Invoice # field. Reference field isn't available.

**Comment by SidneyAllen** [comment]
@andrews05 - reviewing the API docs for Overpayment, I don't see "Reference" as an available property.

So, is this an API feature request or are you calling out an error in our documentation as you see a reference field being returned in the Overpayment object?

**Comment by andrews05** [comment]
Oh you're right, sorry I didn't even check that. There's already a suggestion on the uservoice for this: https://xero.uservoice.com/forums/5528-accounting-api/suggestions/7773063-implement-support-for-the-reference-field-in-the-n
