### ISSUE TITLE
Add summaryOnly (true/false) optional arg to GET Contacts

### ISSUE THREAD

**Issue by SidneyAllen** [XeroAPI/Xero-OpenAPI#403]
https://developer.xero.com/documentation/api/contacts#summary-only

When set to true, this returns lightweight fields, excluding computation-heavy fields from the response, making the API calls quick and efficient. 

https://github.com/XeroAPI/xero-node/issues/523

**Comment by SerKnight** [comment]
Closed in xero-node 🥳  with 4.11.3

via: https://github.com/XeroAPI/Xero-OpenAPI/pull/404
