### ISSUE TITLE
Prepayments missing Payments field

### ISSUE THREAD

**Issue by andrews05** [XeroAPI/Xero-OpenAPI#405]
Hi

Prepayments are currently missing the list of Payments associated with them.
I've double-checked this one, it is in the docs :)

CreditNotes and Overpayments both include this already.

**Comment by SidneyAllen** [comment]
Thanks @andrews05 - addressed in release 2.11.1
https://github.com/XeroAPI/Xero-OpenAPI/releases/tag/2.11.1
