### ISSUE TITLE
A bug my transactions are going to other people's account

### ISSUE THREAD

**Issue by rsam036** [XeroAPI/Xero-OpenAPI#514]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by RettBehrens** [comment]
Hi @rsam036 could you please provide steps to replicate? Additionally, please reach out to api@xero.com for further assistance

**Comment by RettBehrens** [comment]
Account appears to be spamming multiple repos with empty issues and PRs. Closing issue
