### ISSUE TITLE
Country in Organisation Address

### ISSUE THREAD

**Issue by winterlimelight** [XeroAPI/Xero-OpenAPI#556]
## Expected Behavior
Until recently, the country field at ROOT.Organisations[0].Addresses[0].Country returned from https://api.xero.com/api.xro/2.0/Organisation would be the written country name: e.g. "Australia", "United States"

## Current Behavior
Starting late April or early May, this has started returning a value of the form "CNTRY/" + country-short-code. e.g. "CNTRY/AU", "CNTRY/AR".

This is 1. an unexpected change, and 2. inconsistent with the yaml and documentation (https://developer.xero.com/documentation/api/accounting/types/#addresses--1) which says 
```
Country:
          description: 'max length = 50, [A-Z], [a-z] only'
```
i.e. a forward slash is not permitted.

## Possible Solution
We note the UI for entering Organisation Settings has changed, with the country now in a drop-down list, and wonder if this is flowing through to the values.

## Steps to Reproduce (for bugs)
1. Set country in Organisation Settings > Address
2. Call https://api.xero.com/api.xro/2.0/Organisation

## Context
We process this data when verifying an organisation and would like to know if this is a permanent change or an accidental one likely to be revoked? Either way, we presume at this stage we will have to handle both formats.

**Comment by russell-xero** [comment]
@winterlimelight thanks for the heads-up - not an intentional change, and we believe we've fixed it. Hopefully you no longer see this behaviour - please let us know if that's not the case.
