### ISSUE TITLE
API Limits / Bulk interface

### ISSUE THREAD

**Issue by cameronbraid** [XeroAPI/Xero-OpenAPI#58]
The XML interface provides creating multiple items at a time - like Invoice, CreditNote or Payment.  I cant see an equivalent with the open-api versions.  Is this something we can expect ?

Are the same API limits in place for openAPI as there are for XML ?

Thanks

**Comment by SidneyAllen** [comment]
Hi @cameronbraid 

Can you share a bit more about your situation?  Are you working with our Java SDK or using the OpenAPI spec for some other purpose?

I've tested the JSON request body for Invoices and it support multiple invoices being created just like XML.

Right now we are focused on refining the spec for use with OpenAPI-generator to build our SDKs in a more programmatic way.  Our approach to the SDKs is to convert native objects to JSON when interactive with Xero's API.  We don't intend on supporting XML in our official SDKs long term as our new APIs (projects, etc) are JSON only.  It doesn't make sense to support both XML and JSON parsing/unmarshalling in the SDKs when the developer only interacts with the native objects.  Does that make sense?

I've removed the XML out of the OpenAPI spec - is there a reason you need those request/responses in XML?
