### ISSUE TITLE
Empty array with status 200 is returned when calling /connections endpoints

### ISSUE THREAD

**Issue by yinlam22** [XeroAPI/Xero-OpenAPI#585]
We found out that when we are using a valid access token(not expired) to call the `/connections` endpoints it will return us an empty array with status 200. And we suspect because of this, other Xero API we called is returning status 403 with messages AuthenticationUnsuccessful. We have checked that the App is actually connected

## Current Behavior

here is the result when we called `/connections` endpoints
![image](https://github.com/XeroAPI/Xero-OpenAPI/assets/117242008/7e365f1b-63e5-4ac9-a7a7-db6264754e0b)

here`s the screenshot of the connected APP from Xero dashboard
![image](https://github.com/XeroAPI/Xero-OpenAPI/assets/117242008/43bca618-0b85-47ff-9d36-d1485b528cdb)

we also double checked the access token expired time and it is still valid at the time we test

to me this issue seems like it is disconnected on Xero end but on our end it is still showing connected but we dont have a way to refresh this connection

**Comment by Sallyhornet** [comment]
I suspect that the token is valid but the connection has been deleted.  

I can see that there are two Xero organisations with the same name, one is deleted, one is active. Both were connected by different users and I suspect that you are using the access token for the user who connected the deleted organisation.

Tokens are per user per app, not per connection and so if a connection is deleted the access token can still be refreshed in case the user has connected multiple Xero organisations and wants to access the remaining connections. In this case, the user only authorised one connection and this is why your access token has not expired but can't be used.

If you have lost the access token from the other user, the only option is to ask a user to go through the steps to connect the active organisation to your app. They can disconnect the other connection first if they wish to avoid confusion. The disconnection is done from Settings > Connected apps in Xero.

**Comment by Sallyhornet** [comment]
A case can be raised with Xero Support [here](https://developer.xero.com/contact-xero-developer-platform-support) if this does not resolve the issue
