### ISSUE TITLE
AU Payroll API LeaveApplicationID changes when a request is in Scheduled status

### ISSUE THREAD

**Issue by mackerelsky** [XeroAPI/Xero-OpenAPI#590]
For some reason a leave request in the AU payroll API has a different LeaveApplicationID when the request is in scheduled status from processed or rejected status. The processed and rejected statuses both have the same LeaveApplicationID, but the ID changes when the request moves into scheduled, and then changes back when it moves out of scheduled status. LeaveApplicationID seems like it should remain constant regardless of the status of the leave request.

**Comment by Sallyhornet** [comment]
This is a behaviour in Xero and is not related to the SDK.

When a leave is first requested it exists as a LeaveRequest entity only, and has its own id.

When a requested leave is approved, an EntitlementAdjustment entity gets created, with its own id, which is the new LeaveApplicationID that is returned in the approval response, and should be used for any interactions with that leave after that point.

When an approved leave is Rejected, the EntitlementAdjustment record is removed, and the original LeaveRequest remains with an updated status for historical purposes. At that point the LeaveApplicationID that gets returned should be the original id.
