### ISSUE TITLE
Define parameter serialisation

### ISSUE THREAD

**Issue by judgej** [XeroAPI/Xero-OpenAPI#91]
Here is just one example, but it is in many places.

Contacts can be fetched in bulk using the `IDs` query parameter and supplying a comma-delimited list of contact IDs. The OpenAPI description (in particular the accounting API v2.0) does not define this.

The query parameter for the contact IDs is defined:

```json
        {
          "in" : "query",
          "name" : "IDs",
          "description" : "Filter by a comma separated list of ContactIDs. Allows you to retrieve a specific set of contacts in a single call.",
          "schema" : {
            "type" : "string"
          }
        }
```

No validation middleware or code generator is going to be able to handle this parameter as anything other than a plain string. Parsing the IDs from into and comma-delimited lists is then left up to the application domain, when this is plainly something that should be handled by the API client.

Using this as the parameter description changes all that:

```json
        {
          "in" : "query",
          "name" : "IDs",
          "description" : "Filter by a comma separated list of ContactIDs. Allows you to retrieve a specific set of contacts in a single call.",
          "schema" : {
            "type": "array",
            "items": {
              "type": "string"
            },
            "minItems": 1
          },
          "explode": false,
          "style": "form"
        }
```

Now generated code accepts an array of contact IDs. The generated code knows that this array is to be serialised into a comma-delimited list, and does so automatically. Any request validation layer knows this too and can check the parameter is appropriatly formatted. The schema can go further by defining the item format as a uuid, then even more validation can be done.

That is all for free, out of the box. Code generators know how to use it. Message validators know how to use it. The application does not need to mess around with serialising lists of IDs into strings that *ONLY* the API transport needs to know anything about.

Is this something - i.e. the extra steps in the OpenAPI description to define the reality of these parameters - you would be prepared to support?

**Comment by SidneyAllen** [comment]
Hi @judgej 

Thanks for sharing this feedback.  Sounds reasonable.  We will need some time to test how this change will impact our current efforts to generate client SDKs.   I'll tag this as a future enhancement and leave this issue open.

**Comment by SidneyAllen** [comment]
Hi @judgej 

We have merged our oauth2 branch into master.  This includes changes to the objects you called out for improved datatype.
