### ISSUE TITLE
Error not in list (feed-already-co...')

### ISSUE THREAD

**Issue by judgej** [XeroAPI/Xero-OpenAPI#96]
There are a number of errors listed here:

https://github.com/XeroAPI/Xero-OpenAPI/blob/master/bankfeeds-yaml/Xero_bankfeeds_1.0.0_swagger.yaml#L819

We just got an additional error message *'feed-already-co...'* (sorry, only got the first bit of the message before an exception on the OpenAPI client was throw). I am guessing this is saying "[another] feed already connected to this bank account",

The scenario was: creating a bank feed for a bank sort-code/account number, matching an account that already existed, and that already had a bank account.

(That should never normally happen, but the online bank system happened to give us the same account details by random from both sandbox and production, so we accept it is reasonable that this fails. However, it's just that the error code is not listed in the OpenAPI spec that I am mainly raising. We can work around this in the meantime by checking the bank account exists first and checking if it has a feed.)

**Comment by JamesColemanXero** [comment]
I just grabbed this from our logs, @SidneyAllen the full error was:

"status":"REJECTED","error":{"type":"feed-already-connected-in-current-organisation","title":"Feed Connection Failed","status":409,"detail":"The AccountToken, AccountNumber or AccountId is already connected to another Xero Bank Account in the selected Xero Organisation."

**Comment by judgej** [comment]
Thanks James, that's the one: `feed-already-connected-in-current-organisation`.

The OpenAPI client we use validates all the message payloads going in and out, and this one failed the validation coming in, meaning the response was unexpected and could not be trusted. Once this error code is in, we can regenerate our API client code and be ready if this ever happens again.

**Comment by SidneyAllen** [comment]
I've added the error type

**Comment by judgej** [comment]
Thank you all for such a [speedy response](https://github.com/XeroAPI/Xero-OpenAPI/commit/2476b6fd7a83ffce46c018fcca56c15a2afa07b3#diff-e8def0bc053f2a7b6568ea59edc617b3) and update :-)
