### ISSUE TITLE
Setup endpoint not included

### ISSUE THREAD

**Issue by wobinb** [XeroAPI/Xero-OpenAPI#97]
The Setup endpoint documented here: https://developer.xero.com/documentation/api-guides/conversions isn't included within the specification. Can it be included?

**Comment by SidneyAllen** [comment]
@wobinb - at this time the Setup endpoint only supports XML.  Our OAuth 2.0 SDKs are JSON only and do not support serializing and deserializing of XML.

@admo26

**Comment by MatthewSteeples** [comment]
@SidneyAllen Can you leave this issue open until it is implemented, or is it being deprecated going forwards? With just over 12 months until OAuth 1 is no longer supported apps that are using this endpoint (who's sole purpose is to bring you new customers) are going to end up scrambling to transition so we could do with knowing when it's likely to be available

**Comment by SidneyAllen** [comment]
@MatthewSteeples - I'll leave this open.  To be clear an endpoint not being supported in the SDK does not mean it is deprecated.  

I've raised this with the API team to get into their backlog - hopefully it can be solved soon.

In the meantime, there is nothing stopping you from rolling your own code for this one endpoint using an off the shelf OAuth 2.0 library.

**Comment by MatthewSteeples** [comment]
@SidneyAllen Thanks for that. If this endpoint isn't likely to be JSON capable before the deadline we could do with advance notice of that so that we can roll our own.

**Comment by admo26** [comment]
Hey Matthew,

It's not something we'll get done in the next month or so but should be done by mid-year (sorry just lots of other things to do!). It will be well before the OAuth1.0a deprecation date anyway.

Hopefully that helps you plan your roadmap :) 

Adam

**Comment by MatthewSteeples** [comment]
It does indeed help. Thanks. Appreciate there's a lot going on (we're in the same boat, which is why I wanted to try and find out in advance if we were going to have to commit resources to this)

**Comment by SidneyAllen** [comment]
@MatthewSteeples and @wobinb 

We've added the /setup endpoint and related schema components in version 2.4.3
https://github.com/XeroAPI/Xero-OpenAPI/releases/tag/2.4.3

This change has been rolled into the Java SDK v 4.3.5 and will be added to other official SDKs in the coming days/weeks.
