### ISSUE TITLE
BatchPayment::Type property is an enumerated value

### ISSUE THREAD

**Issue by judgej** [XeroAPI/Xero-OpenAPI#98]
The Accounting API `Type` property for the `BatchPayment` model is defined as a string with no limits. The description of this property identifies two values it can be set to:

> PAYBATCH for bill payments or RECBATCH for sales invoice payments

It is useful to defined properties like this with `enum` values, as this helps when generating code from the spec - all the constants (handy when filtering) and validation comes for free.

See:

https://github.com/XeroAPI/Xero-OpenAPI/blob/master/accounting-yaml/Xero_accounting_2.0.0_swagger.yaml#L18640

**Comment by SidneyAllen** [comment]
@judgej - thanks for the feedback.  ENUMS added
